{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "deepsigma.fullname" . }}
  labels:
    {{- include "deepsigma.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "deepsigma.componentLabels" (dict "component" .Values.serviceMonitor.endpoint.service "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.endpoint.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
