{{- if and .Values.dataPersistence.enabled (not .Values.dataPersistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deepsigma.dataPvcName" . }}
  labels:
    {{- include "deepsigma.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.dataPersistence.accessModes | nindent 4 }}
  {{- if .Values.dataPersistence.storageClassName }}
  storageClassName: {{ .Values.dataPersistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dataPersistence.size | quote }}
{{- end }}
