{{- if and .Values.secret.enabled .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deepsigma.secretName" . }}
  labels:
    {{- include "deepsigma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
